version: '3.8'
services:
  db:
    image: postgres:15
    container_name: coupang_pg
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpass
      POSTGRES_DB: coupang
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "55432:5432"

  backend:
    build:
      context: ./backend
    container_name: laravel_app
    restart: always
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: coupang
      DB_USERNAME: youruser
      DB_PASSWORD: yourpass

  frontend:
    build:
      context: ./frontend
    container_name: vue_app
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host

  python-scraper:
    build:
      context: ./python-scraper
    container_name: python_scraper
    restart: always
    volumes:
      - ./python-scraper:/app
    ports:
      - "8001:8001"
    environment:
      PYTHONPATH: /app
      PYTHONUNBUFFERED: 1

